Basic Python

1. Split this string

In [ ]:
S= "Hi there pitchurags!"
S.split()

['Hi', 'there', 'pitchurags!']

2. Use .format() to print the following string.
   Output should be: The diameter of Earth is 12742 Kilometers.


In [ ]:
planet = "Earth"
diameter=12742

In [ ]:
result= "The diameter of {planet} is {diameter} kilometers.".format(planet=planet,diameter=diameter)
print(result)

The diameter of Earth is 12742 kilometers.


3. In this nest dictionary grab the word 'Hello'

In [ ]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


Numpy

In [ ]:
import numpy as np

4.1 Create an array of 10 zeroes?

4.2 Create an array of 10 fives?

In [ ]:
array_zero=np.zeros(10)
print(array_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array_five=np.ones(10)*5
print(array_five)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all the even integers from 20 to 35

In [ ]:
li_even= [x for x in range(20,35,2)]
print(li_even)

[20, 22, 24, 26, 28, 30, 32, 34]


6. Create a 3X3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
matrix_three=np.arange(0,9).reshape(3,3)
print(matrix_three)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatenate a and b


In [ ]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print(np.concatenate((a,b), axis=None))

[1 2 3 4 5 6]


8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import numpy as np
array_random=np.random.randint(10,size=(3,2))
print(pd.DataFrame(array_random))

   0  1
0  2  1
1  0  2
2  7  2


9. Generate the series of dates from 1st Jan 2023 to 10th Feb 2023

In [ ]:
import datetime
start_date= datetime.date(2023,1,1)
end_date=datetime.date(2023,2,10)
delta=datetime.timedelta(days=1)

while start_date<=end_date:
  print(start_date)
  start_date+=delta

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


10. Create a  2D list to Dataframe

lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',26]]

In [ ]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',26]]

In [ ]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',26]]
df=pd.DataFrame(lists,columns=['S.No','Name','Value'])
print(df)

   S.No Name  Value
0     1  aaa     22
1     2  bbb     25
2     3  ccc     26
